### ISSUE TITLE
Odd behavior of MKDA/KDA kernels with odd radii

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#10]
The MKDA and KDA kernels use code I took from Neurosynth, and return weird results when I use an odd radius on a 2mm template. I haven't run it on a 1mm template yet, but I plan to soon. The image below shows what I'm talking about. [Here](https://github.com/tsalo/NiMARE/blob/dce372dabe4494cbc0da9d9c66d0208428b058ae/nimare/meta/cbma/kernel.py#L143-L151) is the current version of the kernel generation code.
![mkda_ma_maps](https://user-images.githubusercontent.com/8228902/38935162-9c5be258-42eb-11e8-9f18-8628f1c2618e.png)

**Comment by tyarkoni** [comment]
IIRC stuff like this happens because when there's a small number of studies, the chi-square test statistic (and any derivative p, z values, etc.) can only take on one of a small set of discrete values. So the results cannot look smooth. That alone doesn't explain the weird speckling pattern, which could in principle due to a bug of some kind in the sphere-growing code, or a precision error somewhere. But I have a vague recollection that this exact issue has come up before, and that I decided after looking into it that it wasn't actually a bug, but a strange artifact of the analysis procedure. Definitely worth looking into again though.

**Comment by tsalo** [comment]
The images above are just the foci for one experiment convolved with the sphere, so I think it must be a problem with the sphere-growing code rather than the meta-analysis code. I plan to take a look at the code, since it's much faster than nltools' equivalent function, but it's a pretty dense seven lines.

**Comment by tyarkoni** [comment]
Just looked at this briefly, and I suspect it's a bug introduced when numpy changed the way it handles floats a year or two ago. The solution is to replace the division operations where `r` is an operand with integer division (i.e., `/` --> `//`). I haven't comprehensively tested this, so you may want to compare it to the output from nltools to make sure it's sound, but it passed basic sanity checks for me.

**Comment by tyarkoni** [comment]
So, just for clarity, this:

```python
xx, yy, zz = [slice(-r / vox_dims[i], r / vox_dims[i] + 0.01, 1) for i in range(len(ijk))]
```

Becomes this:
```python
xx, yy, zz = [slice(-r // vox_dims[i], r // vox_dims[i] + 0.01, 1) for i in range(len(ijk))]
```

**Comment by tsalo** [comment]
That fixed it. Thanks!
Here are the updated MA maps from above:
![mkda_ma_maps](https://user-images.githubusercontent.com/8228902/39200540-714cee12-47ba-11e8-8539-fbdb300dc02b.png)
