### ISSUE TITLE
Search methods to support in Datasets

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#109]
Since NiMARE Datasets should support coordinates, images, annotations, and metadata, searching will be more involved than it is in Neurosynth (I assume). Currently I'm working on a few methods based on the data type.

For coordinates, we want to be able to search by an ROI mask or a coordinate based on distance or a fixed radius.

For annotations we can have searches based on full labels with a threshold for each label's value (since some annotation methods return weights instead of binary yes/no decisions), as well as more web-like searching.

For images, we need to be able to search based on image type (T, Z, contrast, etc.). Other than that, I'm not sure how one would typically search a Dataset for relevant images based on characteristics of the images themselves.

Is there any other metadata we should explicitly make searchable?

**Comment by tyarkoni** [comment]
While it's going to be a pain in the ass, I think it wouldn't be crazy to use a SQLite database internally to represent all the data. I'm currently working on transitioning PyBIDS to a database-backed solution, and I suspect a lot of that will be fairly generalizable (the models will be different, of course). So maybe hold off for the time being? Otherwise we risk writing a lot of internal querying code that becomes obsolete or gets rewritten when the spec changes.

Probably still worth thinking about what a sensible search API would look like, though.

**Comment by tsalo** [comment]
Wow, that's awesome! I'm happy to hold off on major changes, although I want to implement some simple placeholder search methods in the meantime. I've started on that in #107, but won't do anything  that can't be easily replaced. I can just stick to a couple of self-contained methods like `get_studies_by_label`, `get_studies_by_coordinate`, and `get_studies_by_mask`.

**Comment by tyarkoni** [comment]
I'm increasingly thinking that extensive searching/filtering is something we want to do in a centralized way to the degree possible. I.e., instead of the Neurosynth model, where you have a maximal local dataset that you then slice up for analysis, I think we probably want to aim for users doing most of the dataset construction using other tools, and then initializing a Dataset instance from a JSON file that's pretty close to final. There should still be a few helper utilities for filtering, but my view is that we should consider the process of constructing a NIMADS dataset mostly out of scope.

Part of the reason for this is that centralized filtering is cheap (unlike analysis), and if we can get people to use web-based tools to do the selection and editing, then we can do things more scalably, reproducibly, and cumulatively.

With that in mind, I would suggest *not* supporting things like coordinate-based search in NiMARE. Or at least, I think a better approach would be to (eventually) make a call to a client library that interacts with the web. In my current thinking, a centralized service (which could be Neurosynth, or a separate microservice) would fill this role. That allows NiMARE to continue to represent data internally using a very thin model, while pushing the complexity of efficient search and aggregation on to a centralized service (that would automatically ingest from NeuroVault, NeuroScout, editing tools like MetaCurious, etc.).

**Comment by tyarkoni** [comment]
After thinking about it some more, I think I'd like to double-down on the above and suggest that we make `Dataset` instances immutable, and strip them of most of their current functionality, so that in essence they're just lightweight containers around JSON, with a bunch of accessor methods to get out specific kinds of data (e.g., coordinates, images, etc.). We can probably also get rid of the data models (`Study`, `Contrast`, etc.)—I think this is overkill. In essence all we really need are methods to parse the JSON on-demand (possibly with caching).

Under this approach, there would be a clean separation between the construction of datasets and their  use in estimation. The former could potentially still be included in NiMARE, but at minimum I think it would make sense to structure them as completely separate subpackages. In effect, everything will be forced to go through a NIMADS JSON document.

I'll open a separate issue for discussion in the next day or two motivating this approach a bit more, and laying out some other general thoughts about architecture. (I anticipate having much more time to work on this in the next few months now that I've started work on next-gen Neurosynth.)

**Comment by tsalo** [comment]
Would making Datasets immutable conflict with methods that involve searching through a database, like coactivation-based parcellation and functional decoding? Or could those operate through other mechanisms than user-facing search methods? The chi-square-based functional decoding methods both index and compare studies within the database, for example.

**Comment by tyarkoni** [comment]
Nope, won't be a problem. Those are read-only operations.

That said, I do think that stuff should ideally be split off too—i.e., you first search through some store of data (whether local or remote), which returns a `Dataset` (or JSON that can be read into one), and then you decode or parcellate on that. For meta-analytic comparisons, you could pass in two separate `Datasets`. (Might be worth renaming `Dataset` to `Collection` or something.)

**Comment by tsalo** [comment]
I believe that the search methods implemented in #107 and #121 are enough for the internal querying necessary for tools like CBP and meta-clustering, and since the user-facing search methods will be implemented elsewhere, I think I can close this.
