### ISSUE TITLE
Default to taking var_maps instead of se_maps?

### ISSUE THREAD

**Issue by tyarkoni** [neurostuff/NiMARE#161]
Many of the estimators currently accept `se_maps`. I think we should probably take `var_maps` and `sample_sizes` by default, and then compute the SEs internally when needed. Asking users to pass SEs introduces an extra step given that most packages will by default output variances rather than standard errors.

**Comment by tsalo** [comment]
That sounds good to me. I think the only reason we're using `se_maps` now is because those are what came in the 21 pain studies' NIDM results.

**Comment by tsalo** [comment]
Since our only test dataset with associated contrast and variance maps is the NIDM pain one, which has standard error maps, I think we'll also need to implement automatic transforms with the Estimator input validation steps. That would also be helpful when contrasts have T-maps that could be converted to z-statistics.

**Comment by tyarkoni** [comment]
Sounds good. In view of the other thread though, I think we need to get some clarity though on whether the maps in that dataset are SD or SE maps, because that will affect the transformation. @cmaumet, do you know off-hand?

**Comment by tsalo** [comment]
With the transition to PyMARE and with the addition of the `nimare.transforms` module, I think this is pretty much solved (i.e., we can expect users to transform their variance-related images to varcope before running IBMAs), so I'm going to close.
