### ISSUE TITLE
Integrate peaks2maps

### ISSUE THREAD

**Issue by chrisfilo** [neurostuff/NiMARE#20]
Current home: https://github.com/chrisfilo/peaks2maps

- Export U-Net model as SavedModel
- Add Peaks2mapsKernel class to https://github.com/neurostuff/NiMARE/blob/master/nimare/meta/cbma/kernel.py
- The fitted model is large (500Mb) - we will need to put it on OSF and download it when it's needed

Q: Should we host code for retraining the model here as well? @tsalo @tyarkoni

**Comment by tyarkoni** [comment]
I think this would work well as part of the tools for importing/working with datasets... e.g., we could add conversion methods on some of the `Dataset` classes to convert from coords to images, wrapping peaks2maps.

**Comment by chrisfilo** [comment]
I thought this is what `KernelEstimator` classes are suppose to do?

**Comment by tsalo** [comment]
@chrisfilo Regarding using `KernelEstimator` or some other base class, should maps reconstructed with `peaks2maps` be analyzed with coordinate- or image-based tools? I was thinking that that might affect how we integrate `peaks2maps`, given that `KernelEstimator` is linked to the CBMA algorithms.

As far as including tools for retraining goes, I think it would be good to have the code included in `NiMARE`, but I don't think we _have_ to have it if it would be too much work to incorporate it.

**Comment by chrisfilo** [comment]
Best,
Chris


On Mon, Jun 4, 2018 at 7:07 AM Taylor Salo <notifications@github.com> wrote:

> @chrisfilo <https://github.com/chrisfilo> Regarding using KernelEstimator
> or some other base class, should maps reconstructed with peaks2maps be
> analyzed with coordinate- or image-based tools? I was thinking that that
> might affect how we integrate peaks2maps, given that KernelEstimator is
> linked to the CBMA algorithms.
>
It's not clear at this point. On one side the method generates images with
values at all locations in the brain. On the other side the values are
always in the range of -1 to 1 and permutation based testing (potentially
similar to to one in gingerale) will be necessary to deal with biases.

> As far as including tools for retraining goes, I think it would be good to
> have the code included in NiMARE, but I don't think we *have* to have it
> if it would be too much work to incorporate it.
>
Yes we could split this task.

Some followup questions:
1.  Do KernelEstimator classes take coordinates in voxel or mm? Where is
the conversion made?
2. Right now data input is not well documented. Is creating a Database
object necessary to each time?

BTW - here's an example of the current peaks2maps API
https://github.com/chrisfilo/peaks2maps/blob/147a2e52644d3ef0ca7c9cd0e12b1d951c5f87c5/notebooks/sleuth_output.ipynb

**Comment by tsalo** [comment]
> 1.  Do KernelEstimator classes take coordinates in voxel or mm? Where is
the conversion made?

The KernelEstimators use pandas DataFrames in the same general format as Neurosynth uses (i.e., one row for each coordinate). The coordinates need to be in voxels, because the Dataset initialization converts mm coordinates to voxel indices using the mask image selected. The DataFrames can also include additional columns beyond the required `id`, `i`, `j`, and `k`, such as `n` (for `ALEKernel` and `MKDADensity`) or `inference` (for `MDKADensity`), so if `peaks2maps` needs anything else (although it doesn't look like it from your notebook), we can include it.

> 2. Right now data input is not well documented. Is creating a Database
object necessary to each time?

At the moment, a Dataset (but not a Database) is necessary, but if I want to work around that for coordinate-based analyses only I just define a `DummyDataset` class. The coordinate-based tools just need two things from the Dataset, a `coordinates` attribute which is the pandas DataFrame with, at minimum, the columns `i`, `j`, `k`, and `id`, and a `mask` attribute which is a `nibabel.Nifti1Image` for a mask.

We should probably discuss simplifying things (e.g., split the `Dataset` argument in each of the CBMA tools into the coordinates and mask arguments). I actually started doing that in #15 [here](https://github.com/tsalo/NiMARE/blob/f0f2eb2f6ff10c2ec8e02970706a4c9dbef8ff24/nimare/meta/cbma/kernel.py#L22), but that's still open for review and could easily be changed back to how it is in `master`.

**Comment by chrisfilo** [comment]
Any chance you could share an example JSON file you used in one of the
notebooks? It would help me wrap my head around the Dataset class.

**Comment by chrisfilo** [comment]
Awesome - thanks! I'll try to code up ALE style txt importer on the flight
to Singapore.

**Comment by tsalo** [comment]
I don't know if this will help at all, but [here](https://github.com/NBCLab/pyale/blob/1350ba1501ef693ae817542040d4ea515d957f88/pyale/dataset.py#L130) is a function that converts the Sleuth text files to a completely different kind of dataset object. The parts for splitting the experiments and extracting coordinates could be useful I guess.
