### ISSUE TITLE
Drop sample size from Dataset.coordinates

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#231]
Currently, we store sample sizes in both the `Dataset.metadata` and the `Dataset.coordinates` attributes. We should drop the `n` column in `Dataset.coordinates` and make sure that CBMA algorithms grab that info from the metadata instead.

NOTE: Originally part of #179, but that PR sprawled and will probably be closed.

**Comment by nicholst** [comment]
Please forgive me if we've discussed this before, but have we considered (at least in the architecture if not the current implementation) the possibility of voxel-wise-varying sample size?

It's now an edge case, but with larger and larger N (for an individual, non-meta analysis), you have the problem of ever eroding analysis mask since all voxels are required.  We are now building tools that allow the number of subjects contributing to an analysis vary by voxel (within limits, of course).

**Comment by tsalo** [comment]
@nicholst Apologies for closing the issue with #232.

I don't know if we've discussed it, but I don't remember talking about it.

Is this something that would apply to CBMA methods, or just IBMA ones? For CBMAs, I'm guessing that the adjustment would be more of a guess, while for IBMAs, that information could actually be accessible.

I should note that, while sample size is not stored in the Dataset's coordinates dataframe (it's in the metadata one instead), at the point where the CBMA estimator operates on the data, sample size (and any other relevant metadata) will be in the dataframe. So any adjustment done internally within the estimator will still have access to that info.

**Comment by nicholst** [comment]
> Is this something that would apply to CBMA methods, or just IBMA ones? For CBMAs, I'm guessing that the adjustment would be more of a guess, while for IBMAs, that information could actually be accessible.

Oh, sorry!  This is *only* for IBMA.

**Comment by tsalo** [comment]
Gotcha. I think it would be good to open an enhancement issue for this once it's ready then.

**Comment by tsalo** [comment]
I've opened #274 to continue discussion of handling missing data, and will change the title and summary for this issue to match the bug of unknown cause.
