### ISSUE TITLE
Subsampling-based ALE subtraction analysis

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#241]
In a couple of recent papers ([Gu et al., 2019](https://www.sciencedirect.com/science/article/pii/S0149763418307772?via%3Dihub); [Poudel et al., 2020](https://www.sciencedirect.com/science/article/pii/S0376871620300491#sec0010)), a new subsampling-based version of the ALE subtraction has been implemented to account for unbalanced groups.

It seems to me that the additional subsampling is unnecessary, as the standard method should be able to account for unbalanced groups just fine, but I'd like to get others' thoughts on it and see if we should add it to NiMARE.

First, I'll start with a description of the ALE subtraction method, as it is implemented in NiMARE:

1. Define voxels to analyze for group 1 > group 2 and group 2 > group 1 contrasts based on significant voxels from group 1 ALE and group 2 ALE, respectively.
1. Calculate ALE values for group 1 and group 2 datasets.
1. Calculate ALE-difference scores (group 1 ALE - group 2 ALE), restricted to selected voxels from first step.
1. Build voxel-wise null distributions of ALE difference scores using N permutations via the following procedure:
    a. Randomly shuffle group assignments for experiments across both groups.
    a. Calculate ALE values for each new "group".
    a. Calculate ALE-difference scores for the two shuffled groups.
1. For each selected voxel, determine `p` and `z` values for real ALE-difference scores from null distribution of ALE-difference scores.

Here's the description of the subsampling method from Poudel et al. (2020):

>To identify brain regions showing differential activity convergence between studies involving substance using versus non-using participant samples, we employed a permutation-based technique previously utilized for assessing two unequally-sized sets of contrasts/coordinates (Eickhoff et al., 2016, 2009; Gu et al., 2019). Specifically, the two datasets under consideration involved 40 contrasts from 29 papers among substance non-using samples (Table S4) and 25 contrasts from 14 papers among substance using participant samples (Table S5) probing risky-DM. **In general, this permutation technique involved: 1) randomly sub-sampling both datasets to a number equaling 90 % of the total contrasts in the smaller dataset, 2) calculating thresholded ALE images separately for both datasets, and then 3) performing a contrast analysis between the now equally-sized groups. These steps were repeated 500 times and each voxel’s frequency of reaching significance was recorded.**
>
>More specifically, the following operations were performed for each of the 500 permutations. **First, both datasets were randomly sub-sampled to a number equaling ∼90 % of the total contrasts in the substance user dataset (i.e., to n = 22 contrasts per group). Second, whole-brain ALE images for both groups of contrasts were computed, and multiple comparisons correction was separately performed for each group (user and non-users) using a Monte Carlo approach with 10,000 iterations to construct a null distribution (as described above). The ALE images generated from each of the 500 permutations were then thresholded (pvoxel < 0.001, cluster-extent pFWE-corrected < 0.05). Third, for the contrast analysis (users vs. non-users), the two groups’ unthresholded ALE statistic maps were subtracted to generate voxel-wise ALE difference scores. A Monte Carlo procedure was then used to create a null distribution of 10,000 maximum ALE difference scores after randomly shuffling activation foci between datasets. Only those voxels with an ALE difference score greater than the 95th percentile of the null distribution (pFWE-corrected < 0.05) were retained for each of the 500 permutations. In sum, this permutation procedure yielded 500 separate thresholded ALE images for both the substance user and non-user datasets and 500 thresholded ALE difference score maps (users vs. non-users). Finally, each of these three types of maps were binarized and summed to produce a voxel-wise frequency (f) of significance map compiling the outcomes from each of the 500 permutations.** While a similar meta-analysis in the context of ambiguous-DM may provide additional insight into brain alterations among users versus non-users, we focused on risky-DM given our a priori interest on risky-DM and that a sufficient number of ambiguous-DM contrasts among substance users could not be identified in the literature.

**Comment by tyarkoni** [comment]
I agree I don't really see the point of subsampling here; it doesn't seem like different N's should be a problem, but I didn't read carefully.

I'm a bit concerned about (1) in your description of ALE, however. If you start by defining voxels for the A vs. B contrast based on whether they're significant in A alone or B alone, you're heavily biasing the results, no? I could see a (bad) argument for using sub-sampling to mitigate that bias (under the assumption that by fixing N you're equalizing power in both groups), but the more sensible thing to do would be to use a non-circular procedure to select voxels. But maybe I'm missing something. Is there any good reason not to use all voxels in the A/B contrast, other than computational efficiency?

**Comment by nicholst** [comment]
I agree that subsampling rarely makes sense, but I assumed that the motivation was that ALE statistic is not normalised, so that if you got equal proportion of studies in each group, you might find ALE differences if the group sizes are different?

It also points to the problem that ALE value is really a type of statistic about rejecting a null hypothesis of homogeneity... comparisons of test statistics are always a bad idea.

**Comment by tsalo** [comment]
Thank you both for responding so quickly!

> If you start by defining voxels for the A vs. B contrast based on whether they're significant in A alone or B alone, you're heavily biasing the results, no? I could see a (bad) argument for using sub-sampling to mitigate that bias (under the assumption that by fixing N you're equalizing power in both groups), but the more sensible thing to do would be to use a non-circular procedure to select voxels. But maybe I'm missing something. Is there any good reason not to use all voxels in the A/B contrast, other than computational efficiency?

I think it does bias the results, but I believe that the decision to exclude non-significant voxels was a practical one. Apparently, if there is any convergence in a voxel for one group, and none for another, the contrast results become highly significant, even when the first group would not find anything near significant convergence at that voxel.

> I agree that subsampling rarely makes sense, but I assumed that the motivation was that ALE statistic is not normalised, so that if you got equal proportion of studies in each group, you might find ALE differences if the group sizes are different?

I hadn't thought of that, but that does make sense. ALE isn't normalized, so the raw difference scores _would_ be biased toward the large group in cases of equal levels of convergence. But wouldn't that be reflected in the empirical null distribution from the standard contrast analysis as well?

> It also points to the problem that ALE value is really a type of statistic about rejecting a null hypothesis of homogeneity... comparisons of test statistics are always a bad idea.

Whoa... I hadn't really thought of it like that.

**Comment by tyarkoni** [comment]
> I think it does bias the results, but I believe that the decision to exclude non-significant voxels was a practical one. Apparently, if there is any convergence in a voxel for one group, and none for another, the contrast results become highly significant, even when the first group would not find anything near significant convergence at that voxel.

If this is right then it sounds like a pretty good reason not to trust ALE subtraction at all, which accords with @nicholst's concern. There's no reason to think the bias would disappear for voxels that *are* significant for group A; it's just that the fact that you've already called them significant would hide the bias. If there isn't good simulation data showing that the procedure maintains the nominal error rate (or at least something close to it), I feel pretty strongly that we shouldn't include it in NiMARE. If we implement it, people will use it, and they likely won't have any clue about what's going on under the hood. (This kind of thing is a big part of the reason I eliminated the "custom analysis" functionality from neurosynth.org a few years ago.)

**Comment by tyarkoni** [comment]
On thinking about this a bit more, it's not clear to me where the bias you describe would be coming from. Under the assumption that studies are exchangeable between groups (which seems reasonable), I think the p-values from the permutation analysis should be valid, even though the null distribution itself is likely to be biased away from 0 if the groups have different sizes. Are you sure this wasn't a problem only for earlier versions of ALE subtraction where the null was generated by randomizing activations in space, as opposed to permuting group membership? If that's correct (i.e., this is no longer a problem), then I'm fine keeping ALE subtraction in NiMARE. But in that event we should definitely drop the constraint that only significant values are analyzed, because that will definitely introduce a (strong!) bias.

**Comment by nicholst** [comment]
The issue is just about units.  The ALE statistic is *roughly* like a sum of kernel density estimates.  The null hypothesis is that the 'population' ALE for group 1 map is equal to the population ALE group 2 map.  If the *count* of studies is equal then this null hypothesis will be true; but if the *proportion* of studies is equal you'll violate the null when n_1 and n_2 are unequal.  This is exactly the concern for the random shuffling of group (I wasn't assuming random spatial shuffling).

This is why I assumed someone would sub-sample to get equal sample sizes so that sums and proportions are the same thing.

**Comment by tyarkoni** [comment]
@nicholst yes, that makes sense. My comment above was directed at @tsalo. I think we're talking about two different issues. I didn't realize that we're currently selecting voxels for A vs. B comparison based on showing significant effects for A or B alone, which is unrelated to the question of how to interpret a difference in ALE scores. The current voxel selection procedure is clearly circular, and will produce biased p-values (on the assumption that one corrects only for included voxels, and not the whole brain). I was trying to figure out where the justification for that came from, as I don't see any reason the current permutation analysis implementation would justify it. My guess is it's a hold-over from earlier versions of ALE subtraction.

In any case, as long as we eliminate the biased selection procedure, I'm fine leaving things as-is (I agree that interpretation of the subtraction analysis is hard, but that's the user's problem, I don't see it as a software issue). (@tsalo, if computational efficiency is an issue, let's touch base next week or the week after—I'm pretty sure we can optimize `ALESubtraction` quite a bit.)

**Comment by tyarkoni** [comment]
BTW, @tsalo, at bare minimum (and preferably soon) we should generate a warning when users use the current `ALESubtraction` implementation. AFAICT from a quick glance, it doesn't look like they have any way of knowing that voxels that show A > B or B >A are a strict subset of (A || B). I assume we give back whole-brain maps, so the current approach will give a naive user the impression that there just weren't any other voxels that showed differences, when actually the algorithm never even looks at other voxels.

**Comment by tsalo** [comment]
@nicholst, I believe that the empirical null distribution accounts for the problems with units, though. If the dataset counts are the same, and the proportions are the same, then the ALE difference score null distribution should be roughly centered around zero. If the dataset counts are different (let's say dataset 1 has many more studies than dataset 2) but the proportions are the same, then ALE scores should skew positively, but then so should the null distribution, right?

@tyarkoni Right, sorry, I meant that the voxel selection does sound like it would be biased, but the null distributions are derived voxel-wise, so I think the two elements are independent. I can add a warning to the ALESubtraction soon (before the next release), and can even update the Estimator's masker to reflect that it's only some voxels. I _don't_ think computational efficiency is a major concern, and I haven't tried running it without the voxel selection, so I don't know if that's still a concern. I could try it though.

If it does turn out that running the standard subtraction analysis _without_ voxel selection does produce weird results in edge voxels, then would you both prefer to have me implement the subsampling or retain the voxel selection?

**Comment by nicholst** [comment]
@tsalo First let me say I haven't read the two papers you referenced, but, now that I worked out two cases, it *might* be OK.

Taking as a given that ALE is approximately an addition of kernels and not an average, we can do the following:   Suppose at some location we have group A with 4 in 10 studies with foci, and group B has 4 in 100 studies with foci, then the observed A-B difference in ALE maps should be about zero; under null random permutation, however, you have (on average) in group A 8/110*10 ≈ 1 in 10 studies with foci and in group B 8/110*100 ≈ 7 in 100 studies with foci; so your A-B null ALE distribution will be shifted quite negative you'll have evidence that zero is much larger than expected by chance and reject the null in favor of A>B.

Now, if consider equal rates: group A has 4 in 10 studies with foci, group B has 40 in 100 studies with foci; your ALE difference map will have A << B, but under null permutation expecting group A to have 44/110*10 = 4 in 10 studies and group B to have 44/110*100=40, and you should get ALE difference maps with similar characteristics as the observed, and you shouldn't reject the null.


So... OK... it's doing something sensible by the magic of permutation!  Am I understanding the methods correctly?

So, even though the ALE maps are 'wrong' for the task at hand (IMHO) by being based on sums instead of averages, permutation saves you by having a null distribution driven equal proportions under the null.

**Comment by tsalo** [comment]
@nicholst Absolutely, that is my understanding of the standard ALE subtraction analysis.

**Comment by tsalo** [comment]
I think the issues with the standard ALE subtraction method have been figured out, and the issue with voxel selection will be handled by #245. Given that the empirical null distribution _should_ be valid and that circular voxel selection will soon be eliminated, can either of you see any benefit to the subsampling wrapper described in the first comment?

**Comment by tyarkoni** [comment]
Nope, I'm fine ignoring those papers and closing this.

**Comment by tsalo** [comment]
Sounds good to me!
