### ISSUE TITLE
Build 0.0.3-specific models for users

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#255]
I'm going to make a couple of resources specific to 0.0.3 for users and upload them to the OSF.

Some of the resources:
- GCLDA model trained on Neurosynth abstracts
    - 200 topics, 2 ROIs per topic, symmetric. Other parameters held at defaults.
- Neurosynth database converted to NiMARE format, with standard tf-idf features, Cognitive Atlas terms, and basic expanded Cognitive Atlas terms.
- NeuroQuery database converted to NiMARE format, with associated tf-idf and count features.
- LDA model trained on Neurosynth abstracts
    - 200 topics. Other parameters held at defaults.

Anyone who's interested, please comment with other models you'd like to have ready access to, and I'll see if I can upload them. Going to hopefully close this issue within a week.

**Comment by tsalo** [comment]
Neurosynth+Cognitive Atlas --> https://osf.io/aedmu/download

**Comment by royhaast** [comment]
Hi,

Thanks a lot for this package! I've been trying to train a GCLDA model myself using the entire Neurosynth dataset but run into memory issues (even after allocating 125 GB of RAM). So, I'm very interested in downloading the pre-trained model. I found that https://osf.io/b2ycs/ should have this, but I can't locate the actual file (i..e, `neurosynth_gclda.pkl.gz`). Would it be possible to upload this pre-trained model? Otherwise, I will open a different issue for help to fix the memory problem.

Thanks!

**Comment by tsalo** [comment]
I didn't end up training and uploading a GCLDA model due to the same issues. However, @JulioAPeraza is training a model right now, so hopefully he'll be able to upload the trained version once it's ready.

Unfortunately, when I restructured GCLDA from [`tsalo/gclda`](https://github.com/tsalo/gclda) (which is a fork of the original tool), I somehow managed to slow it down substantially 😬. I'm still hoping to clean it up at some point, but in the meantime if you need a model of your own you could use that code instead.

**Comment by royhaast** [comment]
Thanks a lot for the clarification! Ok, I'll be looking forward to download that trained model but in the meantime I'll explore the other option.
