### ISSUE TITLE
New module for simulating data

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#308]
This stems from https://github.com/neurostuff/NiMARE/issues/241#issuecomment-638967169 (sorry @tyarkoni, I only just caught this part of your comment).

> On a related note, I'm thinking it might not be a bad idea to add a module for fake data generation (and maybe some associated functions to run Monte Carlo simulations). We should probably be systematically evaluating our estimators before/as we add them. (Also, this could be easily turned into a paper at some point.)

**Comment by jdkent** [comment]
Hi @tsalo and @tyarkoni, 

I wanted to get your opinions on where simulation code should go within the project.
I spoke with Tal, and I believe he would like another module (perhaps named `simulation.py`) to be placed at [top level of the package](https://github.com/neurostuff/NiMARE/tree/master/nimare).

what are your thoughts?

**Comment by tyarkoni** [comment]
@tsalo, for context, the idea is to start building a framework for more systematic testing of various estimators and utilities, so that we can get some basic insight into how well different methods are working (and make sure they all seem to produce sane outputs under a range of scenarios). The proximal objective is to keep it very simple and generate some fake CBMA data and then run it through all the compatible estimators and quantify how well the outputs converge, etc.

Re: @jdkent's question, for data-generating utilities, I think a top-level `generate` module seems reasonable. Though we could also start smaller (maybe just put things in `utils`) and then expand/move as needed. There are also two other elements that aren't immediately relevant, but that might already be worth anticipating:

*  One or more Jupyter notebooks providing useful profiling/diagnostics of supported methods. Could be a standalone notebook in, e.g., `examples` for now, but maybe eventually we should have a `reports` folder or something like that.
* A set of test utilities that mediate between the data generation utilities and the actual tests. Probably this can just be folded into the standard py.test functionality (e.g., as fixtures) and isn't something we need to give any special thought to right now.
