### ISSUE TITLE
KDA does not work with FWECorrector(method='montecarlo')

### ISSUE THREAD

**Issue by jdkent** [neurostuff/NiMARE#350]
error message:
```
TypeError: correct_fwe_montecarlo() got an unexpected keyword argument 'voxel_thresh'
```
similar to issues #349 and #348

**Comment by tsalo** [comment]
I think the problem is just that the method doesn't have a `voxel_thresh` argument. There's a passing test that uses the Monte Carlo FWE correction for `KDA`:

https://github.com/neurostuff/NiMARE/blob/58e6e82e3ca15ae89390bbf4c294b44f689bd5a0/nimare/tests/test_meta_mkda.py#L94-L95

That said, it's probably worth it to double-check the original KDA paper(s) and see if we can just pass the KDA kernel to an `MKDADensity` Estimator, since the core method might be equivalent. If it _is_ different, I'd like to document how and why that is the case, so we can definitively say that the interface (and parameters) should be different as well.

**Comment by tsalo** [comment]
While I still need to check the original papers, in the mean time, do you want to just update the tests and examples to drop the `voxel_thresh` argument so they pass?

I also accidentally added a `bug` label. I don't think this is as much a bug as an idiosyncratic interface that we _may_ want to improve, so I'm going to switch from `bug` to `enhancement`.

**Comment by jdkent** [comment]
got it, should be removing the `voxel_thresh` argument [when necessary](https://github.com/neurostuff/NiMARE/pull/343/files#diff-c15fffeac20344dca58c5a683a4fa8a663ff740d501067247d1329df9dcccb2fR403-R423)
