### ISSUE TITLE
ALE does not work with KDA kernel when peaks are overlapping

### ISSUE THREAD

**Issue by jdkent** [neurostuff/NiMARE#360]
This error:
[`IndexError: index 20000 is out of bounds for axis 0 with size 10010`](https://github.com/jdkent/NiMARE/blob/5b0af04fb5e63905c072edfc9520d749e6dd1547/nimare/tests/test_estimator_performance.py#L160)

occurs when peaks are close together (within the specified radius given to the kernel)

This is why I was only sometimes getting this error, if the peaks are not overlapping, the algorithm works, but when they do overlap, I get the above error.

One potential solution is to force the ALE values to be between 0 and 1 by renormalizing the data, by placing something like the code below [here](https://github.com/neurostuff/NiMARE/blob/db6347569309d580fcd51e044da764bb9b1286ea/nimare/meta/ale.py#L130)

`ale_values  = ale_values / ale_values.sum()`

I do not know if it's guaranteed that the ale_values will always range from 0 to 1 normally, and this may be strange behavior to suggest the greatest area of convergence is between two peaks

Another solution would be to clip the values larger than 1 to be 1, that would make kda behave like mkda.

Finally, my third idea would be to explicitly check for ma_values above 1, and raise an error numbers above 1 are found.

I'm leaning towards clipping since that would allow the ALE+KDA kernel to "work" and should not impact normal function of the ALE+ALEKernel, but I do not have strong opinions on this issue.

**Comment by tsalo** [comment]
I think this issue could also come up when weights are applied to the MKDA or KDA kernels that could increase certain studies' values above one.

>One potential solution is to force the ALE values to be between 0 and 1 by renormalizing the data, by placing something like the code below here
>
> `ale_values = ale_values / ale_values.sum()`

ALE values shouldn't reach 1, so I don't think we want to do this.

>Another solution would be to clip the values larger than 1 to be 1, that would make kda behave like mkda.

I worry that that might just hide the underlying problem, which I fear could be that the ALE score isn't compatible with un-normalized kernels like KDA or MKDA.

> Finally, my third idea would be to explicitly check for ma_values above 1, and raise an error numbers above 1 are found.

I think this is a good immediate solution. Definitely a more informative error than the one we currently get.

I think we could possibly rescale the MA values based on the max possible ALE value, if that value goes above 1. There would be a warning about this behavior, of course, but that way all of the MA values would be rescaled only if not doing so would break everything. This also wouldn't _necessarily_ be dependent on the maximum _observed_ ALE score- just on the max possible one. WDYT?

**Comment by tyarkoni** [comment]
If we don't think there's a good reason for a user to use a KDA kernel with ALE, I think we should probably just raise an exception in that scenario. That said, it's not obvious to me what would be problematic about doing that. At this point, is there any meaningful difference between the ALE and MKDA procedures, save for the kernel (@nicholst?)? Looking at the `ALE` class code, I see nothing that looks ALE-specific; it seems like pretty much everything is generic code for permutation that could be applied to a KDA or MKDA kernel as well.

If that's true—or if there are only minor differences between the two approaches that we could easily parametrize—it seems like we might be able to collapse `ALE` and `MKDADensity` into a single estimator. Or at the very least, to refactor a bunch of the classes so that they all share the same core permutation/correction code, and only implement necessary helper methods.

**Comment by nicholst** [comment]
Maybe throw a warning, but no reason to make it impossible, is my opinion.

>

**Comment by tsalo** [comment]
Now that we have a warning implemented for mismatched estimators and kernels, I think we can close this.
