### ISSUE TITLE
Statistic-to-p conversion can produce infinite values for analytic null

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#403]
The summary statistic-to-p conversion from histograms can result in infinite values (well, p-values of 0 and infinite negative log-10 p-values). I assume this is an issue that can be dealt with in the actual conversion, rather than the histograms.

Somewhat similar to #364.

**Comment by tsalo** [comment]
I think the issue is that we fixed `null_to_p()` but haven't made any corresponding changes for histogram-based conversion. I'm sure that similar fixes could be apply though, perhaps after abstracting the histogram-based stat-to-p conversion out to its own function.

**Comment by tsalo** [comment]
I've got a `nullhist_to_p` function set up (see below), but I'm not sure what we should use to crop extreme values. The analytic solutions don't have an equivalent to the number of permutations, so we can't use that. I suppose we could do something like add 1 to the last bin (the maximum possible value) so that there no p-values of 0 or inf.

```python
def nullhist_to_p(test_values, histogram_weights, histogram_bins):
    """Return p-value for test value against null histogram.

    Parameters
    ----------
    test_values : (V) array_like
        Values for which to determine p-value.
    histogram_weights : (B [x V]) array
        Histogram weights representing the null distribution against which test_value is compared.
    histogram_bins : (B) array
        Histogram bins

    Returns
    -------
    p_value : :obj:`float`
        P-value associated with the test value when compared against the null
        distribution.
    """
    assert test_values.ndim == 1
    assert histogram_bins.ndim == 1
    assert histogram_weights.shape[0] == histogram_bins.shape[0]
    assert histogram_weights.ndim in (1, 2)
    if histogram_weights.ndim == 2:
        assert histogram_weights.shape[1] == test_values.shape[0]

    n_bins = len(histogram_bins)
    step = histogram_bins[1] - histogram_bins[0]  # assume equal spacing

    # Convert histograms to null distributions.
    null_distribution = histogram_weights / np.sum(histogram_weights, axis=0)
    null_distribution = np.cumsum(null_distribution[::-1, :], axis=0)[::-1, :]
    null_distribution /= np.max(null_distribution, axis=0)

    p_values = np.ones(test_values.shape)
    # Get p-values by getting the binned_values-th value in null_distribution
    if histogram_weights.ndim == 1:
        idx = np.where(test_values > 0)[0]
        binned_values = utils.round2(test_values[idx] * step)
        p_values[idx] = null_distribution[binned_values]
    else:
        binned_values = utils.round2(test_values * step).astype(int)
        binned_values[binned_values > n_bins] = n_bins
        # Pair each test value with its associated null distribution
        for i, (x, y) in enumerate(zip(null_distribution.transpose(), binned_values)):
            p_values[i] = x[y]

    return p_values
```

**Comment by tyarkoni** [comment]
I don't know what's conventional for this kind of thing, but I guess I'd lean towards maybe using the mid-point of the bin, rather than the edge. I.e., if a value is in the smallest bin, and the probability of that bin is 0.01, then the mid-point is 0.005, and not 0 or 0.01. But it's worth googling a bit, because there's probably some generally accepted practice.

**Comment by tsalo** [comment]
Ah, but the problem is that the null histogram is converted to a null distribution via a reversed cumulative sum, so it's the _last_ bin with a non-zero weight that determines the maximum summary statistic with a non-zero p-value. My current solution is just to replace p-values of zero in the resulting array with the float epsilon, like we used to for the regular `null_to_p` before #353.

**Comment by tyarkoni** [comment]
I guess I'm not sure which of 2 things is going on:

1. The most extreme bins in the histograms have non-zero probability, but the value we're trying to look up appears to be outside of the range of the histogram.

2. The target value is within the theoretical range of the histogram, but happens to be more extreme than all of the null values.

If it's the former, then the problem is with the bins, and you would need to extend them in either direction as you proposed, so that they include all possible values. If the latter, then I think we should replace 0 not with epsilon, but with half the step size—i.e., the Nyquist limit. For values smaller than that, we can't determine whether the probability is really 0, or whether it's just very small. But we know that if the value was any larger, it would be rounded up into the next bin, and our result would then be more extreme.

**Comment by tsalo** [comment]
It's definitely the second situation. 

> If the latter, then I think we should replace 0 not with epsilon, but with half the step size—i.e., the Nyquist limit.

Oh that's a cool solution. I hadn't even considered it. I will update #409!

**Comment by tsalo** [comment]
I thought I understood the proposal, but after trying to implement it I think there's a problem. If we have a null histogram with integer bins (as in typical KDA), then half a step size would be 0.5. I don't think it makes sense to set extremely significant p-values to 0.5.

**Comment by tsalo** [comment]
What about cropping extreme values to the largest observed value in the null distribution?

**Comment by tsalo** [comment]
@tyarkoni any thoughts? Did I misunderstand your proposal or should we use something like the largest observed value?

**Comment by tyarkoni** [comment]
Sorry, catching up on this thread; my suggestion was indeed bad. I'm still not sure what the optimal solution is, but I like your last suggestion better than any of the above, so let's go with that for the time being.
