### ISSUE TITLE
Test mismatched images and coordinates in Dataset

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#408]
We need to test behavior when a Dataset contains coordinates from only a subset of the studies.

This is related to #405 and #402. In #405, @jdkent identified a bug when there are _no_ coordinates, while in #402, I identified a bug in how MA maps were returned from a Dataset. If testing does identify a bug, then the solution may be to drop invalid studies automatically, as we do for images. Also see #204.

**Comment by tyarkoni** [comment]
I'm wondering if maybe we shouldn't drop studies automatically, as this might fly under the user's radar, and the results could end up failing to reflect what the user thought they did. An alternative suggestion would be to implement a class method on a `Dataset` called something like `drop_invalid_studies()`, and then, if a test identifies mismatching studies, raise an exception describing the problem and saying something like "either manually resolve the problem or call drop_invalid_studies() to automatically remove studies with mismatched data". We could potentially also add an initialization argument to `Dataset` that does the same thing, though I lean towards forcing an explicit method call, as that way we can inject some important information into the exception method (e.g., "X out of Y studies have apparent mismatches").

One potential complication is that I don't think the NIMADS spec currently imposes any requirement that there actually be an obvious mapping between images and coordinates. While it's hard to imagine a common use case where there would be a legitimate divergence, it's not unthinkable that, e.g., a user might want to treat coordinates like a processed version of the corresponding image, so that it might superficially look like there's a mismatch when actually additional metadata or documentation make it clear what's going on. Not sure what, if anything, we can do about that.

**Comment by tsalo** [comment]
>We could potentially also add an initialization argument to Dataset that does the same thing, though I lean towards forcing an explicit method call, as that way we can inject some important information into the exception method (e.g., "X out of Y studies have apparent mismatches").

I think a study's validity is dependent on the Estimator being used. We already handle mismatched sets of images implicitly (though #204 will make that explicit), and I see the issue of mismatched images and coordinates as a similar problem, rather than an issue of overall Dataset validity.

**Comment by tyarkoni** [comment]
Oh, I see. I think I misunderstood—the title of the issue made me think you meant mismatches between the images and coordinate data for a given study (e.g., that a study has coordinates whose values seem completely at odds with the image values), but you just meant mismatches in *either* images *or* coordinates. Makes sense; ignore my above comment.

**Comment by tsalo** [comment]
I'm noticing that `MetaEstimator._preprocess_input` ignores the `inputs_` attribute in favor of just using the full coordinates DataFrame:

https://github.com/neurostuff/NiMARE/blob/a4ceacd7eabb2ee9fdac7eb85bf8299c142792e6/nimare/base.py#L350-L351

This should only work when _every_ study in the Dataset has coordinates, so it will be good to add tests that cover the case where only a subset of studies have coordinates. Missing images are already covered in the test, AFAIK, so that's less of a concern.
