### ISSUE TITLE
Peaks2MapsKernel+ALE is too memory-intensive for tests

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#417]
Looks like [_compute_null_analytic](https://github.com/neurostuff/NiMARE/blob/59276130bb373389b5aa7d36e2ba351533056a8a/nimare/meta/cbma/ale.py#L99) for the ALE estimator is a source of the increased memory consumption. 
Specifically here: 
https://github.com/neurostuff/NiMARE/blob/59276130bb373389b5aa7d36e2ba351533056a8a/nimare/meta/cbma/ale.py#L147-L151

ALE has 100s of non-zero histogram bins, whereas p2m has 1000s of non-zero bins, creating the variables `ale_scores`, `score_idx`, and `probabilities` with millions of entries.

A potential solution could be to save those variables with single precision (i.e., float32) as opposed to double precision (float64) if there are more than say 2000 `exp_idx` or `ale_idx`. This appears to be meaningful precision loss when computing `score_idx` using `ale_scores` as a float32 or float64 in my example:
```
ale_scores32 = 1 - np.outer(1 - hist_bins[exp_idx], 1 - hist_bins[ale_idx]).ravel().astype(np.float32)
ale_scores64 = ale_scores = 1 - np.outer(1 - hist_bins[exp_idx], 1 - hist_bins[ale_idx]).ravel()

ale_scores32.size # 38529432

score_idx32 = np.floor(ale_scores32 * inv_step_size).astype(int)
score_idx64 = np.floor(ale_scores64 * inv_step_size).astype(int)

(score_idx64 == score_idx32).sum() # 38506719
(score_idx64 != score_idx32).sum() # 22713
```
so this may not be a good solution.

Another potential solution is to turn off/skip tests for ale(analytic)+p2m_kernel since they take too much RAM.

_Originally posted by @jdkent in https://github.com/neurostuff/NiMARE/issues/410#issuecomment-736855179_

**Comment by tyarkoni** [comment]
Personally I'd vote for removing peaks2maps outright. Nobody should really be using it as a kernel in meta-analysis, so I don't think there's much point in testing it, and in general it seems to be increasing our maintenance burden without providing any clear benefit (other than being fun).

**Comment by tsalo** [comment]
I feel like it's a good placeholder for SDM until we have that working.

**Comment by tyarkoni** [comment]
To elaborate on the reasoning: using peaks2maps to turn coordinates into images is sort of like asking a very good artist who's seen a few thousand brain maps to take discrete points and draw a map around them that fits. It's cool as a demonstration, but if you use the result as a basis for any analysis, you're introducing an extremely strong prior that you don't understand, and that would have been different if the artist had been looking at different images just before painting yours. Basically, if you're not comfortable saying "I took the reported coordinates and had my artist friend Jack paint plausible-looking images around them, then I used those in my IBMA", you probably also shouldn't trust peaks2maps.

Re: placeholder, I don't think anything compels us to support untrustworthy functionality just because we have nothing better... IMO the question we should ask ourselves is: if someone used this in a published analysis, would we be able to justify its inclusion in the package? Hard to see how we could do that if we think there's really no valid use case for it in a meta-analysis.

That said, I think I could live with it if we (a) added a warning to peaks2maps so that every time it's run, it spits out a message saying "this is only for fun only and shouldn't be used for serious research" and (b) didn't test or document it in any other context that might imply it's okay for a user to rely on it.
