### ISSUE TITLE
threshold z-map images from Dataset objects to create coordinates

### ISSUE THREAD

**Issue by jdkent** [neurostuff/NiMARE#423]
It would be useful to create coordinates from an image within a Dataset object in circumstances where:
- for some of the studies you only have coordinates, but others you have images
- want to compare an IBMA approach with a CBMA approach when you have images.
This can be accomplished with nilearns [get_clusters_table](https://nilearn.github.io/modules/generated/nilearn.reporting.get_clusters_table.html)

**Comment by tsalo** [comment]
I think this is a great idea, but I have a couple of thoughts:

1. Would applying the same threshold to all image-only studies introduce a bias? 
2. It seems like this would make handling null findings in CBMAs more relevant since there's no guarantee that the images will have any significant clusters.
3. It should be trivial to convert other images types to z-maps before the coordinate extraction too!

**Comment by tyarkoni** [comment]
> Would applying the same threshold to all image-only studies introduce a bias?

Yes in the sense that the distribution of voxel-wise image statistics will be biased (e.g., if you use a low threshold, you'll get more 1's in the MKDA maps than if you use a high threshold). But that's only a problem in the usual "gives people one more knob with which to p-hack" sense. There's no obvious reason why it should bias meta-analysis statistics, because picking a different threshold shouldn't increase the probability of spatial convergence. (Well, except maybe in the sense that at the limit, the null is obviously false everywhere, so with enough non-zero values, the whole brain becomes significant. But that's a separate and much deeper conceptual issue.)

> It seems like this would make handling null findings in CBMAs more relevant since there's no guarantee that the images will have any significant clusters.

Probably a dumb question, but: why are null findings a problem? Can't we just run empty maps through the existing procedures and then they just add a bit of uncertainty? Or is the issue just in the representation of the data—i.e., that we can't tell whether a study is missing coordinates because of null findings, or because of missing data? If it's the latter, maybe we can just adopt a convention that `[]` is different from `null` (or `None` in Python).

> It should be trivial to convert other images types to z-maps before the coordinate extraction too!

+1

**Comment by tsalo** [comment]
> There's no obvious reason why it should bias meta-analysis statistics, because picking a different threshold shouldn't increase the probability of spatial convergence.

That's a relief. Thanks!

**Comment by tyarkoni** [comment]
As an aside, this is something we could potentially follow up on later. I don't expect changes in threshold to bias the estimated values per se, but there should be a (large) effect on the variance of the estimates and the size of the resulting clusters. There is the standard tradeoff here between voxel-wise sensitivity and spatial specificity, and it might be interesting to characterize that. For example, it seems reasonable to suppose that if one has access to the original images, but nevertheless insists on doing a CBMA for some reason, then one is generally better off using a lower rather than a higher threshold to generate peaks—potentially even without any MCC.

@jdkent is working on a workflow to easily run CBMA analyses on coordinates extracted from thresholded NeuroScout maps, and once that's ready it should be pretty trivial to address the above question.
