### ISSUE TITLE
Raise warning if coordinates dataset contains both positive and negative z_stats

### ISSUE THREAD

**Issue by jdkent** [neurostuff/NiMARE#465]
## Summary

Seems weird to perform a meta-analysis with peaks being reported at both the positive and negative thresholds

## Additional details

- NiMARE version: 0.0.7 dev

### What were you trying to do?

Thinking about how users may use the output of #446 

### What did you expect to happen?

Raise warning/error when both positive/negative values are detected in z_stat column?

### What actually happened?

The dataset will run on any estimator

**Comment by tyarkoni** [comment]
It's definitely less common than using unidirectional coordinations, but there *is* a use case for it—e.g., if you have a bunch of contrasts where there's no clear directional hypothesis, but you think a consistent set of regions should be implicated in some way. Since density-based analyses don't care about sign, you will still get sane results, provided you adjust your interpretation appropriately. Neurosynth, for instance, works exclusively like this (though that's more by necessity than design).

So, with that in mind, I don't think we want to raise an error. But a warning does seem appropriate.

**Comment by jdkent** [comment]
Thanks, great point, the interpretation is the crucial step here, not the analysis itself.

**Comment by tsalo** [comment]
I would default to splitting the contrasts within the Dataset during the img-to-coordinate conversion, with a warning. If you wanted to be _really_ fancy, you could also invert the images and save them out as well. So study X's contrast of "A>B" would have positive z-statistic coordinates, and then the conversion would create a new contrast, "B>A" with negative z-statistic coordinates and possibly the inverted images.

Ultimately, though, it seems like a NIMADS/Dataset-searching problem to me. We don't really take into account sign/contrast definition, even with images, in our current approach...
