### ISSUE TITLE
Add image_ids option to `convert_neurovault_to_dataset`

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#496]
## Summary

I think users might find it useful to be able to provide image IDs directly, in addition to collection IDs.

This stems from [this Neurostars post](https://neurostars.org/t/convert-neurovault-to-dataset-in-nimare/19062/5).

## Additional details

It might make direct downloading more straightforward for some users.

## Next steps

1. Discuss
2. Add `image_ids` parameter to `io.convert_neurovault_to_dataset`.
3. Tests.

**Comment by jdkent** [comment]
I'm slightly against this because while sometimes you may only want a single image from each collection (a z-map), other times you may want multiple images (beta, variance, T) from a single collection ([as with this collection](https://neurovault.org/collections/8336/)). We could support both specifying images and collections, but I don't know if that would cause even more confusion since there would be 2 ways to do the same thing (and create more code to maintain).

**Comment by tsalo** [comment]
That seems like a solid reason not to implement this. Want me to close?
