### ISSUE TITLE
Using pre-made MA maps in a meta-analysis is more memory-intensive and slower than making them in `fit`

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#630]
## Summary

We have an argument, `return_type`, in `KernelTransformer.transform` to determine how the modeled activation (MA) maps should be returned. The options are `array`, `image`, and `dataset`. With `dataset`, the transformer creates each MA map and saves it to a file, and then essentially treats the MA map as an "image" to be loaded and masked as needed, instead of creating the MA maps from scratch.

I have an ongoing job that looks at duration and maximum memory usage of the MKDAKernel transformation step and the MKDADensity fit step with different configurations and Dataset sizes, drawing from Neurosynth.

As can be seen in the bottom subplot of the figure below, the red and brown lines, corresponding to MKDADensity models run on a Dataset with pre-generated MA maps, are using _much_ more memory than the green and purple lines, which are running the MKDAKernel to generate MA maps _within_ the meta-analysis, rather than beforehand.

Essentially, I think that loading and masking images takes more time and uses more memory than creating those images from scratch, which seems problematic for large-scale meta-analyses. I will update this as the job increases the Dataset sizes more.

Also, relating to #629, the 500MB memory limit (i.e., `MKDADensity(memory_limit="500mb")`) only has an effect on the meta-analyses using the pre-generated MA maps, and only then when max memory usage is around 13GB (mostly definitely _not_ 500MB).

![profiling_results_v0_0_11](https://user-images.githubusercontent.com/8228902/152603036-e887bd10-cb4e-4e4d-bfac-e50b91c4ac41.svg)

## Additional details

- NiMARE version: 0.0.11

Here's a gist with the script I'm using: https://gist.github.com/tsalo/2f3e28b1608c53e9f171d008f545b447

**Comment by tsalo** [comment]
Also, I don't know why memory usage started dropping for some of the methods at around 780 studies.

**Comment by JulioAPeraza** [comment]
### NiMARE version: 0.0.12

@tsalo The job has been running for 23 days now without any issues. Here are some results:

![n-studies_duration](https://user-images.githubusercontent.com/52050407/191795005-56f7fbf6-ed2c-4dd7-962f-b8c0790aad83.png)
![n-studies_max-memory](https://user-images.githubusercontent.com/52050407/191795027-77f6604e-e1f2-4f96-b0d4-e84a85655220.png)

**Comment by tsalo** [comment]
Thanks! So... it looks like pre-generated MA maps are still slower, but at least now they're not blowing up memory usage. Can you think of any case there they could be useful?

**Comment by JulioAPeraza** [comment]
I think this gap in the Duration comes from the reading algorithm that we currently have. When we added support of sparse arrays for all transformers we change the way the pre-generated maps are loaded. See here https://github.com/neurostuff/NiMARE/blob/main/nimare/meta/cbma/base.py#L223.
Previously, we had `ma_maps = self.masker.transform(self.inputs_[maps_key])` there, but that was memory inefficient and transforming the whole array to sparse was also very slow. So we ended up building the sparse matrix from coordinates for each study.

Perhaps, instead of storing Nifti images, we try to save the `ma_maps` as a sparse array using `sparse.save_npz(out_file, transformed_maps[0])`. I think that can speed up the write/read process; this is, the `meta_estimator.transform` with `return_type="dataset"` and the load of the pre-generated MA maps by `_collect_ma_maps`.

If that shows improvements compare to creating the MA maps from scratch, `CorrelationDecoder` will benefit from reading pre-computed maps; since it will likely have to generate the same MA maps for a different term/topic.

**Comment by JulioAPeraza** [comment]
@tsalo Should we drop support for pre-generated maps? I think users may confuse them as a faster alternative, but it is clearly not that fast compared to generating the maps from scratch. 
And now that `CorrelationDecoder` benefits from parallel computing, I don't see the pre-generated maps as that useful.

**Comment by tsalo** [comment]
It's still less memory-efficient too, right? If so, then I agree. Definitely should drop that functionality.

**Comment by JulioAPeraza** [comment]
Yeah, after saving/loading the MA map as a sparse matrix in a `.npz`, I didn't notice any improvement in memory usage. I will open a PR to drop this functionality. Thanks!

![n-studies_max-memory](https://user-images.githubusercontent.com/52050407/201379981-f40b61d6-95ec-4c81-84e5-2835c65a53d2.png)
