### ISSUE TITLE
Handle sparse/dense uniformly for different kernels

### ISSUE THREAD

**Issue by adelavega** [neurostuff/NiMARE#692]
https://github.com/neurostuff/NiMARE/blob/e0d7cf5dc939729d18c637f1d73ee694acdc6bac/nimare/meta/kernel.py#L202

This line is buggy, because only MKDA return a sparse matrix.

For ALE, this line returns a dense matrix.

In addition, it's worth thinking what we can do to speed things up, as going from data -> sparse then sparse -> costs time

**Comment by JulioAPeraza** [comment]
Yes, in the PR where I introduced sparse arrays I only focused on MKDAChi2 to optimize the CorrelationDecoder. I forgot to mention that I left the other estimators for future PRs. I didn't want to tackle all of the estimators together in a single PR. 
For MKDAChi2 estimator, the code will finish at that line since `return_type == "sparse"`; but, I agree this should be removed when all estimator supports sparse arrays.
