### ISSUE TITLE
plotly graph for reports has large text when report viewed locally

### ISSUE THREAD

**Issue by jdkent** [neurostuff/NiMARE#814]
## Summary

if you view this generated report locally, the text for the diagnostic heatmap is too large
[report.zip](https://github.com/neurostuff/NiMARE/files/11730569/report.zip)

## Additional details

- NiMARE version: 0.1.1

### What actually happened?
![Screenshot from 2023-06-12 23-24-07](https://github.com/neurostuff/NiMARE/assets/12564882/8c82a9e2-201f-47e8-8f8a-ac5012de011d)

## Reproducing the bug

@JulioAPeraza was this a problem you were having earlier when trying to load the different javascript library in an iframe? Or do you think this is more of a case of just needing to give more parameters to the heatmap for it to display the text smaller and the actual heatmap larger?

**Comment by JulioAPeraza** [comment]
If the source file `diagnostics_diag-FocusCounter_tab-counts_figure.html` looks the same, the problem came from `plotly`. I think the issue is that the size of the square is fixed to a size relative to the color bar, so for small tables like the one above it will look like the text is too large.
Should we fix that in a separate PR or we can include it in #809?

**Comment by jdkent** [comment]
I would say fix this in a separate PR.
