### ISSUE TITLE
Documentation site not rendering on GitHub Pages

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#95]
I fixed a couple of issues in the docs that were preventing the site from building locally, which I merged in #94. However, even though the GitHub Pages section in the repository's Settings says that the site is published at https://neurostuff.github.io/NiMARE/, the actual URL doesn't have anything.

Does anyone have any idea why this could be or how we can solve the issue?

**Comment by jdkent** [comment]
I may be out of the loop on how the docs are being built, but AFAIK github pages can only read static html, and won't build the docs for you, if you want to use github pages it looks like you can follow [this guide](https://daler.github.io/sphinxdoc-test/includeme.html), or you can use [doctr](https://drdoctr.github.io/doctr/docs/)

I decided to use readthedocs because it was the only service I could easily version the documentation (so people can check back on v0.1.2 when the latest is on v.1.2.4), you _can_ do versioning with manual workarounds, but readthedocs provides versioning with a simple selection.

I have a short debate with myself about this: HBClab/NiBetaSeries#108

**Comment by tsalo** [comment]
Oooohhh.... I didn't realize GitHub Pages didn't build the html files automatically like RTD does. In that case, I think I'm going to switch over to RTD, at least for now.

Thanks!

**Comment by jdkent** [comment]
Glad I could help!

**Comment by tsalo** [comment]
The site is up now. :tada:
